Repository louketo/louketo-proxy, pull requests merged in 2018-05, with the labels that each got.

#354 Aggressive Timeouts
  config.go
Labels: enhancement

#302 Method check
  utils.go
Labels: bug

#357 Session Only Cookie
  CHANGELOG.md
  README.md
  cookies.go
  cookies_test.go
  doc.go
  handlers.go
  server.go
Labels: documentation, enhancement

#365 Logout Redirection
  handlers.go
Labels: bug

#364 Add support for Strings claim
  README.md
  middleware.go
  middleware_test.go
Labels: enhancement

#370 Debug Profiling Warning
  CHANGELOG.md
  server.go
Labels: documentation

#368 Secure by Default
  CHANGELOG.md
  README.md
  config.go
  doc.go
Labels: enhancement

#346 Add go dep for a better dependency management
  Gopkg.lock
  Gopkg.toml
Labels: enhancement

#374 Golang Version 1.10.2
  .travis.yml
  CHANGELOG.md
  Makefile
Labels: documentation, enhancement

#375 Fix Logout Redirection
  CHANGELOG.md
  doc.go
  handlers.go
  utils.go
Labels: enhancement
